#!/bin/bash

# Specify the directory path
directory="/vpn"
username=$1
password=$2

# Check if the directory doesn't exist
if [ ! -d "$directory" ]; then
    # Create the directory
    mkdir -p "$directory"
    # Set no read, write, or execute permissions
    chmod 000 "$directory"
    echo "Created directory: $directory"
fi

# Create the 'vpn' group if it doesn't exist
getent group vpn || groupadd vpn

# Set minimal permissions for the 'vpn' group on the directory
chown :vpn "$directory"
chmod 070 "$directory"

# Create the user
useradd -m -s /bin/false -g vpn $username

# Set the user's password
echo "$username:$password" | chpasswd
